src: this assert() call was giving me errors for some reason...
Along the lines of:

...
  c++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_DARWIN_USE_64_BIT_INODE=1' -I/Users/nrajlich/.node-gyp/0.8.2/src -I/Users/nrajlich/.node-gyp/0.8.2/deps/uv/include -I/Users/nrajlich/.node-gyp/0.8.2/deps/v8/include -I../deps  -Os -gdwarf-2 -Wnewline-eof -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/nodehiredis/hiredis.o.d.raw  -c -o Release/obj.target/nodehiredis/hiredis.o ../hiredis.cc
  c++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_DARWIN_USE_64_BIT_INODE=1' -I/Users/nrajlich/.node-gyp/0.8.2/src -I/Users/nrajlich/.node-gyp/0.8.2/deps/uv/include -I/Users/nrajlich/.node-gyp/0.8.2/deps/v8/include -I../deps  -Os -gdwarf-2 -Wnewline-eof -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/nodehiredis/reader.o.d.raw  -c -o Release/obj.target/nodehiredis/reader.o ../reader.cc
../reader.cc:223:30: error: expected ')'
            assert((unsigned size_t)index == 1);
                             ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
../reader.cc:223:20: note: to match this '('
            assert((unsigned size_t)index == 1);
                   ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
../reader.cc:223:20: error: cast from pointer to smaller type 'unsigned int' loses information
            assert((unsigned size_t)index == 1);
            ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
2 errors generated.
make: *** [Release/obj.target/nodehiredis/reader.o] Error 1
gyp ERR! rebuild error Error: `make` failed with exit code: 2
gyp ERR! rebuild error     at ChildProcess.onExit (/Users/nrajlich/node-gyp/lib/build.js:215:23)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok